import {
  faFrog,
  faBed,
  faLightbulb,
  faSnowflake,
  faBone,
  faIceCream,
  faFishFins,
  faHotdog,
  faPizzaSlice,
  faBuilding,
  faCat,
  faCrow,
  faBell,
  faDog,
  faHippo,
  faTableTennisPaddleBall,
} from '@fortawesome/free-solid-svg-icons'

export const PASSWORD_OPTIONS = [
  'frog',
  'cat',
  'crow',
  'bell',
  'building',
  'pingpong',
  'dog',
  'hippo',
  'hotdog',
  'fish',
  'bone',
  'icecream',
  'light',
  'pizza',
  'bed',
  'snow',
]

export const passwordIconMap = [
  { icon: faFrog, text: 'frog' },
  { icon: faCat, text: 'cat' },
  { icon: faCrow, text: 'crow' },
  { icon: faBell, text: 'bell' },
  { icon: faBuilding, text: 'building' },
  { icon: faTableTennisPaddleBall, text: 'pingpong' },
  { icon: faDog, text: 'dog' },
  { icon: faHippo, text: 'hippo' },
  { icon: faHotdog, text: 'hotdog' },
  { icon: faFishFins, text: 'fish' },
  { icon: faBone, text: 'bone' },
  { icon: faIceCream, text: 'icecream' },
  { icon: faLightbulb, text: 'light' },
  { icon: faPizzaSlice, text: 'pizza' },
  { icon: faBed, text: 'bed' },
  { icon: faSnowflake, text: 'snow' },
]
